### ISSUE TITLE
新版运行错误

### ISSUE THREAD

**Issue by syscca** [llc1123/ssmgr-trojan-client#417]
/usr/lib/node_modules/ssmgr-trojan-client/dist/config.js:25
        addr: options.listenAddress?.split(':')[0] || '0.0.0.0',
                                    ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/ssmgr-trojan-client/dist/app.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by llc1123** [comment]
node版本过低

**Comment by syscca** [comment]
大佬要什么版本，12.x的

**Comment by llc1123** [comment]
至少14

**Comment by syscca** [comment]
用最新稳定版的行不。

**Comment by llc1123** [comment]
14以上都行
